name: ekyc_id_flutter
description: A Flutter Plugin to interact with EkycID.
version: 1.0.18-beta
homepage: https://ekycsolutions.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  dio: ^4.0.4
  http_parser: ^4.0.1
  flutter_spinkit: ^5.1.0
  flutter_font_icons: ^2.2.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
   
  plugin:
    platforms:
      android:
        package: com.ekycsolutions.ekyc_id_flutter
        pluginClass: EkycIdFlutterPlugin
      ios:
        pluginClass: EkycIdFlutterPlugin
