name: ekyc_id_flutter
description: A Flutter Plugin to interact with EkycID.
version: 1.0.14
homepage: https://ekycsolutions.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  dio: ^4.0.4
  http_parser: ^4.0.1
  just_audio: ^0.9.24
  flutter_beep: ^1.0.0
  flutter_spinkit: ^5.1.0
  flutter_font_icons: ^2.2.4
  vibration: ^1.7.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/ekyc_id_flutter/assets/blink_en.mp3
    - packages/ekyc_id_flutter/assets/look_left_en.mp3
    - packages/ekyc_id_flutter/assets/look_right_en.mp3
    - packages/ekyc_id_flutter/assets/scan_back_en.mp3
    - packages/ekyc_id_flutter/assets/scan_front_en.mp3
    - packages/ekyc_id_flutter/assets/blink_kh.mp3
    - packages/ekyc_id_flutter/assets/look_left_kh.mp3
    - packages/ekyc_id_flutter/assets/look_right_kh.mp3
    - packages/ekyc_id_flutter/assets/scan_back_kh.mp3
    - packages/ekyc_id_flutter/assets/scan_front_kh.mp3
  plugin:
    platforms:
      android:
        package: com.ekycsolutions.ekyc_id_flutter
        pluginClass: EkycIdFlutterPlugin
      ios:
        pluginClass: EkycIdFlutterPlugin
