name: ekyc_id_flutter
description: A Flutter Plugin to interact with EkycID.
version: 1.0.1
homepage: https://ekycsolutions.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ekycsolutions.ekyc_id_flutter
        pluginClass: EkycIdFlutterPlugin
      ios:
        pluginClass: EkycIdFlutterPlugin
