enum FrameStatus {
  PREPARING,
  PROCESSING,

  DOCUMENT_NOT_FOUND,
  DOCUMENT_FOUND,
  DOCUMENT_TOO_BIG,
  DOCUMENT_TOO_SMALL,
  DOCUMENT_NOT_IN_CENTER,

  NO_FACE_FOUND,
  FACE_FOUND,
  FACE_TOO_BIG,
  FACE_TOO_SMALL,
  FACE_NOT_IN_CENTER,
  MULTIPLE_FACES_FOUND,
}
